%% AeroDyn
AeroEditNames = {'Echo','DTAero','WakeMod','AFAeroMod','TwtPotent',...
                 'TwrShadow','TwrAero','FrozenWake','CavitCheck',...
                 'AirDens','KinVisc','SpdSound','Patm','Pvap',...
                 'FluidDepth','SkewMod','TipLoss','HubLoss',...
                 'TanInd','AIDrag','TIDrag','IndToler','MaxIter',...
                 'UAMod','FLookup','InCol_Alfa','InCol_Cl','InCol_Cd',...
                 'InCol_Cm','InCol_Cpmin','NumAFfiles','AFNames',...
                 'ADBlFile_1','ADBlFile_2','ADBlFile_3','NumTwrNds',...
                 'SumPrint','NBlOuts','BlOutNd','NTwOuts',...
                 'TwOutNd','OutList'};

%% BeamDyn
BeamEditNames = {'Echo','analysis_type','rhoinf','quadrature','refine',...
                 'n_fact','DTBeam','NRMax','stop_tol','member_total',...
                 'kp_total','order_elem','BldFile','UsePitchAct',...
                 'PitchJ','PitchK','PitchC','SumPrint','OutFmt',...
                 'NNodeOuts','OutNd','OutList'};

%% ElastDyn
ElastEditNames = {'Echo','Method','DT','Gravity','FlapDOF1',...
                  'FlapDOF2','EdgeDOF','TeetDOF','DrTrDOF','GenDOF',...
                  'YawDOF','TwFADOF1','TwFADOF2','TwSSDOF1','TwSSDOF2',...
                  'PtfmSgDOF','PtfmSwDOF','PtfmHvDOF','PtfmRDOF',...
                  'PtfmPDOF','PtfmYDOF','OoPDefl','IPDefl','BlPitch_1',...
                  'BlPitch_2','BlPitch_3','TeetDefl','Azimuth',...
                  'RotSpeed','NacYaw','TTDspFA','PtfmSurge','PtfmSway',...
                  'PtfmHeave','PtfmRoll','PtfmPitch','PtfmYaw','NumBl',...
                  'TipRad','HubRad','PreCone_1','PreCone_2','PreCone_3',...
                  'HubCM','UndSling','Delta3','AzimB1Up','OverHang',...
                  'ShftGagL','ShftTilt','NacCMxn','NacCMyn','NacCMzn',...
                  'NcIMUxn','NcIMUyn','NcIMUzn','Twr2Shft','TowerHt',...
                  'TowerBsHt','PftmCMxt','PftmCMyt','PftmCMzt','PtfmRefzt'...
                  'TipMass_1','TipMass_2','TipMass_3','HubMass',...
                  'HubIner','GenIner','NacMass','NacYIner','YawBrMass',...
                  'PtfmMass','PtfmRIner','PtfmPIner','PtfmYIner',...
                  'BldNodes','BldFile_1','BldFile_2','BldFile_3',...
                  'TeetMod','TeetDmpP','TeetDmp','TeetCDmp','TeetSStP',...
                  'TeetHStP','TeetSSSp','TeetHSSp','GBoxEff','GBRatio',...
                  'DTTorSpr','DTTorDmp','Furling','FurlFile','TwrNodes',...
                  'TwrFile','SumPrint','OutFile','TabDelim','OutFmt',...
                  'TStart','DecFact','NTwGages','NBlGages','BldGagNd',...
                  'OutList'};

%% ServoDyn
ServoEditNames = {'Echo','DT','PCMode','TPCOn','TPitManS_1',...
                  'TPitManS_2','TPitManS_3','PitManRat_1','PitManRat_2',...
                  'PitManRat_3','BlPitchF_1','BlPitchF_2','BlPitchF_3',...
                  'VSContrl','GenModel','GenEff','GenTiStr','GenTiStp',...
                  'SpdGenOn','TimGenOn','TimGenOf','VS_RtGnSp','VS_RtTq',...
                  'VS_Rgn2K','VS_SlPc','SIG_SlPc','SIG_SySp','SIG_RtTq',...
                  'SIG_PORt','TEC_Freq','TEC_NPol','TEC_SRes','TEC_RRes',...
                  'TEC_VLL','TEC_SLR','TEC_RLR','TEC_MR','HSSBrMode',...
                  'THSSBrDp','HSSBrDT','HSSBrTqF','YCMode','TYCOn',...
                  'YawNeut','YawSpr','YawDamp','TYawManS','YawManRat',...
                  'NacYawF','CompNTMD','NTMDfile','CompTTMD','TTMDfile',...
                  'DLL_FileName','DLL_InFile','DLL_ProcName','DLL_DT',...
                  'DLL_Ramp','BPCutoff','NaxYaw_North','Ptch_Cntrl',...
                  'Ptch_SetPnt','Ptch_Min','Ptch_Max','PtchRate_Min',...
                  'PtchRate_Max','Gain_OM','GenSpd_MinOM','GenSpd_MaxOM',...
                  'GenSpd_Dem','GenTrq_Dem','GenPwr_Dem','DLL_NumTrq',...
                  'SumPrint','OutFile','TabDelim','OutFmt','TStart',...
                  'OutList'',GenPwr','GenTq'};

%% InflowWind
InflowEditNames = {'Echo','WindType','PropogationDir','NWindVel',...
                   'WindVxiList','WindVyiList','WindVziList','HWindSpeed',...
                   'RefHt','PLexp','Filename','RefLength','FilenameRoot',...
                   'TowerFile','FileName_u','FileName_v','FileName_w',...
                   'nx','ny','nz','dx','dy','dz','ScaleMethod',...
                   'SFx','SFy','SFz','SigmaFx','SigmaFy','SigmaFz',...
                   'UReg','WindProfile','PLExp','Z0','SumPrint','OutList'};

%% FAST
FastEditNames = {'Echo','AbortLevel','TMax','DT','InterOrder',...
                 'NumCrctn','DT_UJac','UJacSclFact','CompElast',...
                 'CompInflow','CompAero','CompServo','CompHydro',...
                 'CompSub','CompMooring','CompIce','EDFile',...
                 'BDBldFile_1','BDBldFile_2','BDBldFile_3','InflowFile',...
                 'AeroFile','ServoFile','HyrdoFile','SubFile',...
                 'MooringFile','IceFile','SumPrint','SttsTime',...
                 'ChkptTime','DT_Out','TStart','OutFileFmt','TabDelim',...
                 'OutFmt','Linearize','NLinTimes','LinTimes',...
                 'LinInputs','LinOutputs','LinOutJac','LinOutMod',...
                 'WrVTK','VTK_type','VTK_fields','VTK_fps'};

